**Liabraries**

- librarary : Where the Buit-in-Function  are Stored.
1.  Numpy -> Dimensions
2.  Pandas -> Manipulate the data
3.  Matplotlib -> Visualize
4.  Seaborn -> Statical Knowledge

**Numpy :**
- Numpy is a library which is used to work with dimensionality of the data.Using Built-in-functions:
1. Array
2. arange
3. ndim
4. size
5. shape
6. reshape
7. reshape(-1,1) and reshape(1,-1)
8. zero's
9. One's
10. full
11. eye
12. ravel
13. Transpose
14. random -> Randin
15. random -> random
16. random -> rand
17. random -> random
18. concatenate
19. sum
20. min
21. max
22. axis=1
23. axis=0
24. argmax
25. argmin

In [1]:
# 1. Array :- which is used to create data in the form of dimension
# 1D - One Dimension
import numpy as np

In [ ]:
a=np.array([10,20,30,40,50])
print(a)
print(type(a)) # Checking the datatype
print(a.ndim)  # ndim -> No of dimensional
print(a.shape)  # shape -> Check the number of rows and columns
print(a.size) # size -> Total number of values
print(a[3])

[10 20 30 40 50]
<class 'numpy.ndarray'>
1
(5,)
5
40


In [ ]:
# 2D - Two dimensional Array -> matrix is a 2D
a=np.array([[1,4,7],[1,18,25],[9,7,4]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a[2][0])

[[ 1  4  7]
 [ 1 18 25]
 [ 9  7  4]]
<class 'numpy.ndarray'>
2
(3, 3)
9
9


In [ ]:
# Arange :- Arange Function will be take Staring point to Ending point
#2. arange Function will be give out in 1D(one Dimensional Format)

a=np.arange(11,17)
print(a)
print(a.ndim)

[11 12 13 14 15 16]
1


In [ ]:
# 1D and 2D
a=np.arange(1,61)
print(a)
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60]
1


In [ ]:
b=a.reshape(10,6)
print(b)
print(type(b))
print(b.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
<class 'numpy.ndarray'>
2


In [ ]:
a=np.arange(1,61).reshape(10,6)
print(a)
print(a.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]
2


In [3]:
# Cube :- Doesn't have Rows and Columns(3D)
a=np.arange(1,61).reshape(5,2,6)
print(a)


[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]


In [4]:
print(a[2])

[[25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [5]:
print(a[2][1])

[31 32 33 34 35 36]


In [6]:
print(a[2][1][3])

34


In [12]:
# Reshape(1,-1) #(Rows,Columns)
a=np.array([[10,20,30,40,50],[60,80,70,90,10]])
print(a)
print(a.ndim)
b=a.reshape(1,-1)
print(b)

[[10 20 30 40 50]
 [60 80 70 90 10]]
2
[[10 20 30 40 50 60 80 70 90 10]]


In [13]:
# reshape(-1,1)
b=a.reshape(-1,1)
print(b)

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [80]
 [70]
 [90]
 [10]]


In [14]:
# raval -> Any dimensional array will be converted back to 1D
a=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(a)
print(a.ndim)
b=a.ravel()
print(b)
print(b.ndim)


[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
2
[ 10  20  30  40  50  60  70  80  90 100]
1


In [21]:
# transpose :- Transpose convert into rows to columns and column and rows
a=np.array([[10,4,9],[11,12,13]])
print(a)
print(a.ndim)
b=a.transpose()
print(b)
print(b.ndim)

[[10  4  9]
 [11 12 13]]
2
[[10 11]
 [ 4 12]
 [ 9 13]]
2


In [24]:
#Zeros :- zero's function will be print only the zero's
# default datatype for numpy is float64
a=np.zeros((5,4))
print(a)
print(a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [25]:
# Ones :- The ones Function will be print the only ones
a=np.ones((5,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
#Full :- The full Function will be print the what's the number we print
a=np.full((5,4),8)
print(a)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [29]:
#eye
a=np.eye(7)
print(a)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [30]:
# Random : 1. Randint :- give the specific range mention by the user give the random integer values comes
a=np.random.randint(10,50,5) #(start point,End point,number of values)
print(a)


[44 15 19 29 25]


In [31]:
# 2. rand :- 0 to 1 -> in between 0 to 1 random values will be pick
a=np.random.rand(5,4)#(colums,Rows)
print(a)

[[0.45374891 0.47415245 0.92284526 0.49134209]
 [0.76282905 0.90069235 0.05659265 0.42973933]
 [0.52812263 0.0973398  0.58926802 0.35649589]
 [0.06183186 0.44164112 0.98580808 0.69894925]
 [0.85793794 0.31307295 0.25760947 0.19669317]]


In [32]:
# 3.Randn :- These Function will be give the 1 to -1
a=np.random.randn(5,4)
print(a)

[[-1.38692124  1.26370236  0.52222376 -0.88085191]
 [ 0.30898271 -1.39355968 -0.69398343  1.78623339]
 [ 0.31586221 -0.43223455  0.06868556 -1.23384675]
 [-0.20238222 -1.47095543  1.01227434 -0.65313932]
 [-1.1942399  -0.64100066 -1.04481688  0.37534016]]


In [42]:
# 4. random -> random : same as the rand
a=np.random.random(5)
print(a)


[0.70187239 0.53371317 0.98731944 0.58912096 0.9709976 ]


In [47]:
# Concatination
a=np.array([[1,4,9],[10,7,3],[11,8,7]])
b=np.array([10,5,9])

c=(a+b)
print(c)

[[11  9 18]
 [20 12 12]
 [21 13 16]]


In [48]:
# sum
a=np.array([[10,4,5],[1,4,9]])
print(a.sum())

33


In [53]:
# axis-1 -> Row
#axis -0 -> Column
print(np.sum(a,axis=1)) # row wise


[19 14]


In [52]:
print(np.sum(a,axis=0)) # column wise

[11  8 14]


In [56]:
#max
print(np.max(a))
print(np.max(a,axis=1))
print(np.max(a,axis=0))

10
[10  9]
[10  4  9]


In [57]:
#min
print(np.min(a))
print(np.min(a,axis=1))
print(np.min(a,axis=0))

1
[4 1]
[1 4 5]


In [60]:
# argmax and argmin
print(np.argmax(a))# index value is to be given max value index
print(np.argmin(a))# index value is to be given min value index

0
3


In [61]:
print(np.argmax(a,axis=1)) # Row wise
print(np.argmax(a,axis=0)) # Column wise

[0 2]
[0 0 1]


In [62]:
print(np.argmin(a,axis=1)) # Row wise
print(np.argmin(a,axis=0)) # Column wise

[1 0]
[1 0 0]


In [66]:
print(np.add(a,b))


[[20  9 14]
 [11  9 18]]


In [67]:
# matmul
a=np.array([[1,4,7],[3,8,1]])
b=np.array([[1],[2],[3]])
print(np.matmul(a,b))

[[30]
 [22]]


In [68]:
# loops
a=np.array([[10,4,5],[15,6,70],[14,15,13]])
for i in a:
  print(i)

[10  4  5]
[15  6 70]
[14 15 13]


In [70]:
c=[]
for i in a:
  f=0
  for j in i.tolist():
    f=f+j
  c.append(f)
print(c)

[19, 91, 42]


In [73]:
c=[]
for i in a.tolist():
  c.append([i])
print(c)

[[[10, 4, 5]], [[15, 6, 70]], [[14, 15, 13]]]
